### ISSUE TITLE
Stop or limit audit logs

### ISSUE THREAD

**Issue by filipposc5** [ministryofjustice/logstash-formula#49]
Audit logs are generating a lot of data which is causing a slowdown in the ELK cluster. Opening this issue as one of the suggestions was to stop shipping audit logs. 

https://github.com/ministryofjustice/logstash-formula/blob/master/logstash/client.sls#L9

**Comment by niallcreech** [comment]
This is needed, idea would be to allow pillar enabling disabling of components, which should be simple to implement

something like the below (a rough gist)

client.sls:

    # Default enabled components
    {{ if pillar.get("logstash:salt:enabled", true }}
    {{ logship('salt-minion.log', '/var/log/salt/minion', 'salt', ['salt','salt-minion','log'], 'json') }}
    {% endif %}
    # Optional components default to falise
    {{ if pillar.get("logstash:auditd:enabled", false }}
    {{ logship('audit.log', '/var/log/audit/audit.log', 'audit', ['audit'], 'json') }}
    {% endif %}

Pillar entries similar to the below could then be used

staging.sls:
    
    logstash:
        auditd: true

**Comment by niallcreech** [comment]
Closed by #83. Opening https://github.com/ministryofjustice/platforms-team/issues/102 as the process of actually clearing out all users of auditd shipping
